((emacs-lisp-mode
  (fill-column . 110)
  (indent-tabs-mode . nil)
  (elisp-lint-ignored-validators . ("byte-compile" "package-lint"))
  (elisp-lint-indent-specs . ((describe . 1)
                              (it . 1)
                              (thread-first . 0)
                              (cl-flet . 1)
                              (cl-flet* . 1)
                              (org-element-map . defun)
                              (org-roam-dolist-with-progress . 2)
                              (org-roam-with-temp-buffer . 1)
                              (org-with-point-at . 1)
                              (magit-insert-section . defun)
                              (magit-section-case . 0)
                              (org-roam-with-file . 2)))))
