---
name: Build docs

runs:
  using: composite
  steps:
    - name: Install deps
      run: sudo apt install texinfo

    - name: Build docs
      run: make html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc
